[tool]
[tool.poetry]
authors = ["Darius Brown <dariustb@tech-center.com"]
name = "root"
version = "0.0.0"
description="Flask Stock Comparison Web App"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
robin-stocks = "^1.5.1"
